### PR TITLE
Alpha 3

### PR DESCRIPTION
**Pull request by SirSeim**
We need to make sure most of the stuff we have right now is working and that nothing was broken in the process of merging everything together.

### CODE REVIEW

**Comment by SirSeim** [comment]
Also, I need to know if `databrowser` can be added to `app-test` for this merge

**Comment by SirSeim** [comment]
I need approvals from @cf7 & @NAnguiano that everything looks the way it's supposed to be.

**Comment by NAnguiano** [comment]
The data browser works fine for me and is looking as intended. There's something weird going on on the Front Desk homepage for me, but I'm not sure if it's supposed to look that way. The activity enrollment table is going off the page.

activityenrollmenttable

Console is reporting:
http://localhost:8080/api/dropins/undefined/activities Failed to load resource: the server responded with a status of 500 (Internal Server Error)

**Comment by SirSeim** [comment]
I'm going to work with @lkonchan on that activity enrollment before we merge this

**Review by lkonchan — APPROVED** [review]
Looks great Ed!

**Pull request merged**
